---
dontChroot: false
timeout: 3600
script:
    - command: "bash /home/illuminate/IlluminateBR-OS/scripts/install.sh @@PACKAGECHOOSER_RESULT@@"
      name: "Instalando pacotes e personalizando perfil do IlluminateBR-OS..."
