---
dontChroot: false
timeout: 1800
script:
    - command: "bash /home/illuminate/IlluminateBR-OS/scripts/install.sh @@PACKAGECHOOSER_RESULT@@"
      name: "Instalando softwares e configurando ambiente IlluminateBR-OS..."
