name: Build IlluminateBR-OS ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependências de Compilação Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Habilitar Suporte Desktop no Flutter e Compilar
        run: |
          flutter config --enable-linux-desktop
          chmod +x build_iso.sh
          ./build_iso.sh

      - name: Compactar Artefatos do Build
        run: |
          tar -czvf illuminatebr-os-build.tar.gz iso_root/

      - name: Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: IlluminateBR-OS-Build
          path: illuminatebr-os-build.tar.gz
